"""add delivery partners

Revision ID: 3df78b0aa2d6
Revises: 4db871e44519
Create Date: 2026-09-07 14:42:02.758183

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3df78b0aa2d6'
down_revision: Union[str, Sequence[str], None] = '4db871e44519'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('delivery_partners',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('vehicle_type', sa.String(length=50), nullable=False),
    sa.Column('vehicle_number', sa.String(length=30), nullable=False),
    sa.Column('availability_status', sa.Enum('AVAILABLE', 'UNAVAILABLE', 'ON_DELIVERY', name='delivery_availability_status'), nullable=False),
    sa.Column('current_location', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_delivery_partners_availability_status'), 'delivery_partners', ['availability_status'], unique=False)
    op.create_index(op.f('ix_delivery_partners_id'), 'delivery_partners', ['id'], unique=False)
    op.create_index(op.f('ix_delivery_partners_phone'), 'delivery_partners', ['phone'], unique=True)
    op.create_index(op.f('ix_delivery_partners_vehicle_number'), 'delivery_partners', ['vehicle_number'], unique=True)
    op.add_column('orders', sa.Column('delivery_partner_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_orders_delivery_partner_id'), 'orders', ['delivery_partner_id'], unique=False)
    op.create_foreign_key(None, 'orders', 'delivery_partners', ['delivery_partner_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.drop_index(op.f('ix_orders_delivery_partner_id'), table_name='orders')
    op.drop_column('orders', 'delivery_partner_id')
    op.drop_index(op.f('ix_delivery_partners_vehicle_number'), table_name='delivery_partners')
    op.drop_index(op.f('ix_delivery_partners_phone'), table_name='delivery_partners')
    op.drop_index(op.f('ix_delivery_partners_id'), table_name='delivery_partners')
    op.drop_index(op.f('ix_delivery_partners_availability_status'), table_name='delivery_partners')
    op.drop_table('delivery_partners')
    # ### end Alembic commands ###
