"""add order tracking

Revision ID: 7deb431ccf07
Revises: 3df78b0aa2d6
Create Date: 2026-09-07 14:56:12.295476

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7deb431ccf07'
down_revision: Union[str, Sequence[str], None] = '3df78b0aa2d6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('order_tracking',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'ACCEPTED', 'PREPARING', 'READY', 'PICKED_UP', 'OUT_FOR_DELIVERY', 'DELIVERED', 'CANCELLED', name='tracking_status'), nullable=False),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('remarks', sa.String(length=500), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_order_tracking_id'), 'order_tracking', ['id'], unique=False)
    op.create_index(op.f('ix_order_tracking_order_id'), 'order_tracking', ['order_id'], unique=False)
    op.create_index(op.f('ix_order_tracking_status'), 'order_tracking', ['status'], unique=False)
    op.create_index(op.f('ix_order_tracking_timestamp'), 'order_tracking', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_order_tracking_timestamp'), table_name='order_tracking')
    op.drop_index(op.f('ix_order_tracking_status'), table_name='order_tracking')
    op.drop_index(op.f('ix_order_tracking_order_id'), table_name='order_tracking')
    op.drop_index(op.f('ix_order_tracking_id'), table_name='order_tracking')
    op.drop_table('order_tracking')
    # ### end Alembic commands ###
